linuxdeepin/dde-appearance

src/service/impl/appearancemanager.cpp

设置主题文件时类型应该使用正确的类型
Log: 修复控制中心改变主题显示异常的问题
Influence: 控制中心主题设置
Bug: https://github.com/linuxdeepin/developer-center/issues/3581
Change-Id: Ib8de54e1577d373d27b4e4d7f2574da674cccfdc

修复控制中心设置主题显示异常的问题

---

src/service/impl/appearancemanager.cpp

Log: remove notify, just print info message
resolve: https://github.com/linuxdeepin/developer-center/issues/3729
设计师觉得第一条通知多于了，而且也没有设置消失的时间。。但是日志还是需要的，所以加了info

chore: remove the notify when start

---

src/service/dbus/appearance1thread.cpp
src/service/impl/appearancemanager.cpp

恢复设置后需要更新对应的DBus属性值，让前端去更新界面
Log: 修复调用DBus接口恢复个性化设置失效的问题
Resolve: https://github.com/linuxdeepin/developer-center/issues/3835
Influence: 控制中心个性化设置

fix: 调用DBus接口恢复个性化设置失效

---

src/service/impl/appearancemanager.cpp
src/service/modules/fonts/fontsmanager.cpp

resolve: https://github.com/linuxdeepin/developer-center/issues/3873
代码里面应该判断tmpMonoFont是否存在，可能是开发者那时候头晕，判断了fontList,始终使用了第一位

fix: wrong set for fontconfig

---

src/service/impl/appearancemanager.cpp

控制中心更改主题和外观后,壁纸需要跟随变化
Log: 修复控制中心设置主题壁纸没有跟随改变的问题

fix: 控制中心设置主题壁纸没有跟随改变

---

src/service/modules/fonts/fontsmanager.cpp

There shouldn't be empty lines in the front of a xml file. A wrong format will cause fontconfig parsing config files failure, thus a error of font configuration. Trim the first empty line.
Log: fix the wrong format of fontconfig file

fix: wrong format of fontconfig file

---

dbus/com.deepin.wm.xml

dbus 接口标记为废弃, 调用时会没有返回值, 导致设置壁纸异常
Log: 修复桌面无法设置壁纸的问题
Resolve: https://github.com/linuxdeepin/developer-center/issues/4134
Influence: 桌面壁纸设置

fix: 桌面无法设置壁纸

---

src/service/impl/appearancemanager.cpp
src/service/impl/appearancemanager.h
src/service/modules/subthemes/customtheme.cpp

当桌面壁纸为用户自定义的壁纸时, 主题应该切换为自定义主题
当用户去修改主题的其它选项(非壁纸)时, 桌面壁纸不随主题变化
Log: 修复切换主题外观桌面壁纸被替换的问题
Resolve: https://github.com/linuxdeepin/developer-center/issues/4198

fix: 切换主题外观桌面壁纸被替换

---

src/service/modules/fonts/fontsmanager.cpp

should use path not currentPath
use mkpath
Log: wrong usage of QDir

fix: folder not be created and font not setted

---

src/service/impl/appearancemanager.cpp
src/service/impl/appearancemanager.h
src/service/modules/common/commondefine.h
src/service/modules/fonts/fontsmanager.cpp
src/service/modules/fonts/fontsmanager.h

Use fontconfig configuration to implement different fonts for different languages instead of regenerating
the fontconfig configuration after switching languages.
When resetting font configuration, directly clear
the user configuration instead of overwriting it
with default values.

chore: update font configuration logic

---

src/service/modules/fonts/fontsmanager.cpp

remove the right bracket when format font
Log: fix extra bracket

fix: one more bracket when format font

---

src/service/modules/dconfig/phasewallpaper.cpp

增加壁纸路径判断,壁纸存在才去设置
防止壁纸丢失时导致的白屏问题
Log: 解决alpha 升级到beta 设置壁纸白屏的问题
Resolve: https://github.com/linuxdeepin/developer-center/issues/4303

fix: alpha 升级到beta 设置壁纸白屏

---

misc/dbusservice/CMakeLists.txt
misc/dbusservice/com.deepin.wm.service

提供com.deepin.wm Dbus服务, 防止dde-session-daemon 启动时获取快捷键列表失败
Log: 解决控制中心不显示窗管相关快捷键的问题

fix: 控制中心不显示窗管相关快捷键

---

debian/changelog
debian/control

添加冲突解决升级时与dde-kwin的文件冲突导致安装失败问题
Log:

fix: Add conflicts to solve the problem of file conflicts with dde-kwin during upgrades that cause installation failures

---

src/service/impl/appearancemanager.cpp

用户自定义主题修改的每个选项单独生效, 不影响主题的其他选项
Log: 修复自定义主题切换外观主题的其他选项被修改的问题
Resolve: https://github.com/linuxdeepin/developer-center/issues/4395

fix: 自定义主题切换外观主题的其他选项被修改

---

src/service/dbus/deepinwmfaker.cpp

call kwin reconfigure interface will cause splash screen problem
Log: fix splash screen problem

fix: set theme by dde-control-center will cause splash screen problem

---

src/service/dbus/appearance1thread.cpp
src/service/impl/appearancemanager.cpp
src/service/impl/appearancemanager.h

the workspace count will be 0 when init in constructor
so we should get workspace count when set wallpapers
Log:
Inflence: 桌面壁纸设置
Resolve: https://github.com/linuxdeepin/developer-center/issues/4931

fix: update workspaceCount after org.kde.KWin service is valid

---

src/service/modules/background/backgrounds.cpp

不应该使用图片url, 需要使用解析后的图片地址转换为壁纸图片去设置
Log: 修复看图设置壁纸错误的问题
Influence: 桌面壁纸设置
resolve: https://github.com/linuxdeepin/developer-center/issues/5021

fix: 使用实际的图片路径(地址)设置壁纸

---

misc/systemd/dde-appearance.service.in
src/service/dbus/appearanceproperty.cpp
src/service/main.cpp
src/service/modules/common/commondefine.h

because fakewm block itself, so , this should init before itself, then when appearance is available, it can be accessed

fix: when appearance is register, but it not work

---

misc/systemd/dde-appearance.service.in
src/service/dbus/appearancedbusproxy.cpp
src/service/dbus/appearancedbusproxy.h

dde-appearance depends org.deepin.dde.Timedate1(dde-session-daemon) service so it must depends org.dde.session.Daemon1.service
Log:

chore: auto set theme feature is missing

---

fakewm/dbus/deepinwmfaker.cpp
fakewm/dbus/deepinwmfaker.h

when kwin invoke appearance, appearance invoked fakewm, but fakewm invoke kwin again, then the chain is blocked. so here fakewm will invoke kwin with the way which will not block itself
Log:

fix: fakewm block with kwin when be invoked

---

src/service/impl/appearancemanager.cpp
src/service/impl/appearancemanager.h
src/service/modules/api/utils.cpp
src/service/modules/api/utils.h
src/service/modules/dconfig/phasewallpaper.cpp
src/service/modules/dconfig/phasewallpaper.h

1. check the value when dconfig changed, this will make set not do twice
2. write config file before write to dconfig. Because dde-desktop listen
to dconfig, so we should update config before dconfig changed. And
base config need to be changed before write new dconfig

chore: tidy up the flow

---

debian/changelog
fakewm/dbus/deepinwmfaker.cpp

Log:
1. should use kcminputrc as deepin-kwin used
2. cursorSize should get 24 when never set in kcminputrc

fix: deepinwmfaker read error file

---

src/service/impl/appearancemanager.cpp

it doesn't work immediately after setting setWallpaperSliderShow
Issue: https://github.com/linuxdeepin/developer-center/issues/8178

fix: it doesn't work immediately

---

debian/changelog
fakewm/dbus/deepinwmfaker.cpp
fakewm/dbus/deepinwmfaker.h

Bug: 
https://github.com/linuxdeepin/developer-center/issues/7912
https://github.com/linuxdeepin/developer-center/issues/9068
https://github.com/linuxdeepin/developer-center/issues/9041
Log: fix  control center window effects cannot be control

fix: control center window effects cannot be control

---

src/service/modules/api/themethumb.cpp

The scaled images were not updated to cursor image list.
Issue: https://github.com/linuxdeepin/developer-center/issues/9892
Log: Cursor image not scaled to same size

fix: Cursor image not scaled to same size

---

src/service/impl/appearancemanager.cpp

m_currentGlobalTheme未初始化，导致在appearance定时器触发时，重新设置了壁纸。

chore: 解决开机壁纸自动变更的问题

---

src/service/modules/fonts/fontsmanager.cpp

* 使用 prepend 而非 assign 避免覆盖系统配置
* 因没设置衬线字体的地方，不生成衬线字体的配置

fix: incorrect generated fontconfig configuration

---

fakewm/dbus/deepinwmfaker.cpp

kwin升级后，快捷键的配置中group应该是kwin
Issue: https://github.com/linuxdeepin/developer-center/issues/10292

chore: 解决快捷键无法恢复的问题

---

fakewm/dbus/deepinwmfaker.cpp

由于group变更导致快捷键丢失问题，kwin设置快捷键的group已经还原到之前的deepin-kwin 
This reverts commit 314539ac37e309af0b9ce4194e7b4a1afe84ca68.

Revert "chore: 解决快捷键无法恢复的问题"

---

fakewm/dbus/deepinwmfaker.cpp

由于group变更导致快捷键丢失问题，kwin设置快捷键的group已经还原到之前的deepin-kwin Issue: https://github.com/linuxdeepin/developer-center/issues/10292

chore: 解决快捷键显示为空的问题

---

misc/dconfig/org.deepin.dde.appearance.json
src/service/dbus/appearance1thread.cpp
src/service/impl/appearancemanager.cpp

When the initial value is 9.0, Dconfig will incorrectly parse to int type, resulting in subsequent failure to set as a floating point number
Log:

feat: Use string to store Compact_Font_Size in dconfig

---

src/service/plugin.cpp

deepin-service-manager会注册dbus服务,插件不需要注册
Task:https://pms.uniontech.com/task-view-365061.html

fix:修复dde-appearance不能正常启动

---

src/service/impl/appearancemanager.cpp

插件启动太早，比startdde都早，所以通过xsetting获取不到scale，直接通过gsetting获取缩放。

chore: 解决控制中心个性化中主题图片加载不出来的问题

---

src/service/impl/appearancemanager.cpp
src/service/impl/appearancemanager.h

deepin-kwin的模糊处理会监听opacity,频繁变化会导致kwin卡死，在这里做一下频率变化的限制，同时已通知deepin-kwin处理opacity快速变化导致的卡死问题
Bug: https://pms.uniontech.com/bug-view-286305.html

fix: Quickly adjusting transparency may cause it to get stuck

---

debian/changelog
misc/systemd/dde-fakewm.service.in

拉起dde-fakewm,需要先拉起de-session-pre.target,de-session-pre.target需要重新拉起startdde,导致循环依赖
pms: BUG-292895

fix: 修复系统安装完成后无法进入桌面。输入密码后一直处于加载状态

---

src/service/dbus/appearance1thread.cpp
src/service/impl/appearancemanager.cpp
src/service/modules/subthemes/customtheme.cpp

set the light and dark color to gsettings and dconfig when selecting a global theme
pms: BUG-291243

fix: active color are invalid in different global theme
