src/service/dbus/appearance1adaptor.cpp

remove it as cmake suggest
Log: remove unusedmoc

chore: unusedmoc

---

CMakeLists.txt
src/service/CMakeLists.txt

chore: use gnuinstalldir

---

src/service/impl/fsnotify.cpp

Log: fix error in https://github.com/linuxdeepin/dde-appearance/pull/11

fix: use wrong list in watchGlobalDirs

---

src/service/main.cpp

Log: ApplicationName must be org.deepin.dde.appearance

fix: reset ApplicationName as org.deepin.dde.appearance

---

.reuse/dep5
.tx/config
.tx/deepin.conf
debian/changelog

Changelog
* fix: wrong format of fontconfig file
* fix: 控制中心设置主题壁纸没有跟随改变
* fix: reset ApplicationName as org.deepin.dde.appearance
* fix: 调用DBus接口恢复个性化设置失效
Log:

chore: bump version to 1.0.5

---

dbus/com.deepin.wm.xml
debian/control
src/service/CMakeLists.txt
src/service/dbus/deepinwmfaker.cpp
src/service/dbus/deepinwmfaker.h
src/service/main.cpp

The current project relies on deepin-wm-dbus as an adapter for some interfaces

chore: merge deepin-wm-dbus

---

src/service/dbus/deepinwmfaker.cpp
src/service/main.cpp

use deepin-kglobalshortcutsrc config file.

fix: cannot reset all shortcut keys

---

src/service/impl/appearancemanager.cpp

this make the name of json, style and show missing in json
Log: fix error from font to json

fix: error form font to json

---

src/service/main.cpp

this will bring a formatted log, and append to journal
Log: add dlog support

feat: add dlog support

---

src/service/dbus/deepinwmfaker.cpp

use org.kde.kwin.Compositing.suspend function.

fix: toggle window effect not working

---

src/service/dbus/deepinwmfaker.cpp

This reverts commit daad4a4c0a3471830cec85c33fa803d99740fcda.

Revert "fix: toggle window effect not working"

---

src/service/dbus/deepinwmfaker.cpp

The kwin component binds the names of these configuration files

chore: remove deepin- prefix

---

debian/changelog

* release dde-appearance 1.1.0
Log:

chore: bump version to 1.1.0

---

src/service/modules/fonts/fontsmanager.cpp

backlist only should check for those who have en
Log: backlist logic fix
resolve: https://github.com/linuxdeepin/developer-center/issues/4332

fix: blacklist logic

---

CMakeLists.txt
src/service/modules/api/themes.cpp

Log: fix listCursorTheme when XCURSOR_PATH is set

fix: fix listCursorTheme when XCURSOR_PATH is set

---

.clang-format
.reuse/dep5
src/service/impl/appearancemanager.cpp

设置用户自定义壁纸时，需要先调用dde-daemon的dbus接口去保存自定义的壁纸
Log: 修复用户自定义壁纸保存失败的问题

fix: 用户自定义壁纸保存失败

---

src/service/dbus/deepinwmfaker.cpp
src/service/dbus/deepinwmfaker.h
src/service/main.cpp

fix: deepin-wm-dbus not write theme name

---

src/service/modules/subthemes/customtheme.cpp

fix: https://github.com/linuxdeepin/developer-center/issues/4544

fix config save path of customtheme

---

src/service/dbus/deepinwmfaker.cpp

chore(fakewminterface): missinginteface

---

src/service/main.cpp

Log: fix the case service can be started twice

fix(service): service should not be started twice

---

src/service/impl/appearancemanager.cpp
src/service/impl/fsnotify.cpp
src/service/modules/api/themes.cpp
src/service/modules/subthemes/customtheme.cpp

fix: mkdir should from root

---

CMakeLists.txt
src/service/main.cpp

Log: fix dbus register check failed

chore: check dbus register

---

src/service/impl/appearancemanager.cpp

fix(coredump): Cannot makesure first exist

---

debian/changelog

chore: new tag to 1.1.2

---

src/service/dbus/deepinwmfaker.cpp

Closed: https://github.com/linuxdeepin/developer-center/issues/4401

Fix: wayland can't set wallpaper

---

src/service/modules/background/backgrounds.cpp

background should refresh after set background
Log:
Resolve: https://github.com/linuxdeepin/developer-center/issues/4865

fix: background should refresh after set background

---

debian/changelog

* release dde-appearance 1.1.4
Log:

chore: bump version to 1.1.4

---

src/service/modules/api/themethumb.cpp

fix: cannot get dark png

---

debian/changelog

chore: bump verson to 1.1.5

---

misc/translations/translations/dde-appearance_en.ts
src/service/impl/appearancemanager.cpp

chore: bring back first notification

---

src/service/impl/appearancemanager.cpp

chore: wrong spell

---

debian/changelog

release dde-session 1.1.6
Log:

chore: bump version to 1.1.6

---

CMakeLists.txt
fakewm/CMakeLists.txt
fakewm/dbus/deepinwmfaker.cpp
fakewm/dbus/deepinwmfaker.h
fakewm/main.cpp
misc/dbusservice/CMakeLists.txt
misc/dbusservice/com.deepin.wm.service
misc/dbusservice/com.deepin.wm.service.in
misc/dbusservice/org.deepin.dde.Appearance1.service.in
src/service/CMakeLists.txt
src/service/main.cpp

chore: split deepinwmfaker

---

debian/changelog

release dde-appearance 1.1.7
Log:

chore: release dde-appearance 1.1.7

---

fakewm/main.cpp

chore: correct a typo in main.cpp

---

debian/changelog

chore: bump version to 1.1.8

---

fakewm/dbus/deepinwmfaker.cpp

feat: add window keybindings

---

debian/changelog

chore: bump to 1.1.9

---

src/service/dbus/appearance1.cpp

void should return at once
Log:

fix: return value is void and wait for longtime

---

src/service/impl/appearancemanager.cpp
src/service/impl/appearancemanager.h

now the flow is changed, so every time set, need update fontSize

fix: fontSize not update

---

src/service/impl/appearancemanager.cpp

fix: with flow updated, font need also be updated

---

debian/changelog

chore: bump version to 1.1.20

---

src/service/dbus/appearance1thread.cpp

Issue: https://github.com/linuxdeepin/developer-center/issues/6896

fix: should init then regist the dbus service

---

debian/changelog

chore: bump version to 1.1.21

---

src/service/impl/appearancemanager.cpp

should update the value first, then applyGlobaltheme
Issue: https://github.com/linuxdeepin/developer-center/issues/6933 Log:

fix: globaltheme will set to before one

---

src/service/impl/appearancemanager.cpp

Issue: linuxdeepin/developer-center#6933
Log:

fix: if is auto theme, update property first

---

debian/changelog

chore: bump version to 1.1.22

---

src/service/impl/appearancemanager.cpp

and this function finally go back to itself
Log:

fix: during init, should not invoke any dbus

---

debian/changelog

chore: bump version to 1.1.23

---

src/service/dbus/appearance1.cpp

Issue: https://github.com/linuxdeepin/developer-center/issues/7047 Log:

fix: emit themechange again when themetype changed

---

debian/changelog

chore: bump version to 1.1.24

---

dbus/com.deepin.wm.xml
fakewm/dbus/deepinwmfaker.cpp
fakewm/dbus/deepinwmfaker.h

Log:
Issue: https://github.com/linuxdeepin/developer-center/issues/5685

chore: add signal for deepin fakewm

---

debian/changelog

chore: bump version to 1.1.25

---

src/service/impl/appearancemanager.cpp
src/service/modules/api/sunrisesunset.cpp

使用 Date::startOfDay()
Issues: linuxdeepin/developer-center#7122

fix: automatic dark mode switching time is incorrect

---

src/service/impl/appearancemanager.cpp

start or stop timer in main thread
Issue: https://github.com/linuxdeepin/developer-center/issues/8178

fix: start timer in another thread

---

debian/changelog

chore: bump version to 1.1.27

---

src/service/modules/api/themes.cpp

fix: custom icon theme path incorrect

---

debian/changelog

release 1.1.28
Log: bump version to 1.1.28

chore: bump version to 1.1.28

---

fakewm/dbus/deepinwmfaker.cpp

chore: change global accel component name

---

debian/changelog

bump version to 1.1.30
Log: bump version to 1.1.30

chore: bump version to 1.1.30

---

fakewm/dbus/deepinwmfaker.cpp

notify kwin to reload the config when sync config
Issue: https://github.com/linuxdeepin/developer-center/issues/10016

fix: notify kwin to reload the config when sync config

---

debian/changelog

release version 1.1.31
Log: bump version to 1.1.31

chore: bump version to 1.1.31

---

debian/changelog
src/service/impl/appearancemanager.cpp

chore: bump version to 1.1.32

---

debian/changelog

chore: bump version to 1.1.34

---

debian/changelog

chore: bump version to 1.1.35

---

misc/dconfig/org.deepin.dde.appearance.json
src/service/dbus/appearance1thread.cpp
src/service/impl/appearancemanager.cpp
src/service/modules/common/commondefine.h

According to requirements, compact mode will not affect font size
Task: https://pms.uniontech.com/task-view-362569.html

feat: Compact mode does not affect the font setting range

---

dbus/org.deepin.dde.Appearance1.xml
misc/dconfig/org.deepin.dde.appearance.json
src/service/dbus/appearance1.cpp
src/service/dbus/appearance1.h
src/service/dbus/appearance1thread.cpp
src/service/dbus/appearance1thread.h
src/service/dbus/appearancedbusproxy.h
src/service/dbus/appearanceproperty.cpp
src/service/dbus/appearanceproperty.h
src/service/impl/appearancemanager.cpp
src/service/impl/appearancemanager.h
src/service/modules/common/commondefine.h

add interface for scrollbar policy
Log:
Task: https://pms.uniontech.com/task-view-364175.html

feat: add interface for scrollbar policy

---

.reuse/dep5

chore: 解决CI license 校验通过的问题

---

src/service/modules/api/syncconfig.cpp
src/service/modules/common/commondefine.h
src/service/plugin.cpp

chore: 解决dbus调用，获取不到返回值的问题

---

fakewm/dbus/deepinwmfaker.cpp
fakewm/dbus/deepinwmfaker.h

monitor multitask status signal
Log: monitor multitask status signal
Bug: https://pms.uniontech.com/bug-view-275171.html

fix: monitor multitask status signal

---

debian/changelog

chore: bump version to 1.1.36

---

fakewm/dbus/deepinwmfaker.cpp

add zoom shortcut
Log: add zoom shortcut
Bug: https://pms.uniontech.com/bug-view-273961.html

fix: add zoom shortcut

---

dbus/org.deepin.dde.Appearance1.xml
misc/dconfig/org.deepin.dde.appearance.json
src/service/dbus/appearance1.cpp
src/service/dbus/appearance1.h
src/service/dbus/appearance1thread.cpp
src/service/dbus/appearance1thread.h
src/service/impl/appearancemanager.cpp
src/service/impl/appearancemanager.h
src/service/modules/common/commondefine.h

Add active colors in a dark theme
Bug:https://pms.uniontech.com/bug-view-283171.html 
Log:

fix: active colors are same in different themes

---

debian/changelog

release 1.1.37
Log: bump version to 1.1.37

chore: bump version to 1.1.37

---

debian/changelog

chore: bump version to 1.1.38

---

src/service/impl/appearancemanager.cpp

- scaleFactor default value is 1.0
pms: TASK-368711

fix: the theme thumbnail is empty

---

src/service/impl/appearancemanager.cpp
src/service/modules/api/themes.cpp
src/service/modules/api/themethumb.cpp
src/service/plugin-dde-appearance.json
src/service/plugin.cpp

代码优化调整
Log: 代码优化调整
pms: TASK-368579

fix: 代码优化调整

---

debian/changelog

chore: bump version to 1.1.39

---

src/service/modules/background/backgrounds.cpp

If the file does not exist, it will not be stored in the list
pms: TASK-368711

fix: the wallpaper list may not exist

---

debian/changelog

as title
Log: bump version to 1.1.40

chore: bump version to 1.1.40

---

misc/dconfig/org.deepin.dde.appearance.json
src/service/impl/appearancemanager.cpp
src/service/impl/appearancemanager.h

default global theme change to nirvana
pms: TASK-286399

chore: update default global theme

---

debian/changelog

as title
Log: bump version to 1.1.42

chore: bump version to 1.1.42

---

src/service/impl/appearancemanager.cpp
src/service/impl/appearancemanager.h

This reverts commit b3d36056ce09095055d0c68615f8c0dcc01c4226. kwin侧已经修复原问题, 原提交会导致bug-294895, 故回退
pms: BUG-294895

Revert "fix: Quickly adjusting transparency may cause it to get stuck"

---

src/service/impl/appearancemanager.cpp

update custom active color when change theme type
pms: BUG-295685

fix: wrong active color when changing theme type

---

src/service/impl/appearancemanager.cpp

change compare method to CaseInsensitive
pms: BUG-295687

fix: wrong behivour when clicking active colors

---

src/service/plugin.cpp

QCoreApplication::installTranslator does not
take ownership of translationFile
PMS: bug-288733

fix: translation not effective

---

debian/changelog

release 1.1.43
Log: bump version to 1.1.43

chore: bump version to 1.1.43

---

debian/control
src/service/dbus/appearance1thread.cpp
src/service/impl/appearancemanager.cpp
src/service/impl/appearancemanager.h
src/service/modules/api/themes.cpp
src/service/modules/api/themes.h
src/service/modules/common/commondefine.h
src/service/modules/fonts/fontsmanager.cpp
src/service/modules/fonts/fontsmanager.h

为了升级qt6.8，将xsetting的通过gsetting读取配置改成dconfig读取
Log: 将xsetting的通过gsetting读取配置改成dconfig读取
pms: TASK-369703

feat: 将xsetting的通过gsetting读取配置改成dconfig读取

---

debian/changelog

as title
Log: bump version to 1.1.44

chore: bump version to 1.1.44

---

misc/dconfig/org.deepin.dde.appearance.json

chore: change the default appearance to light

---

debian/changelog

release 1.1.45
Log: bump version 1.1.45

chore: bump version to 1.1.45

---

fakewm/CMakeLists.txt
fakewm/dbus/deepinwmfaker.cpp
fakewm/dbus/deepinwmfaker.h
src/service/CMakeLists.txt
src/service/modules/api/themethumb.h
src/service/modules/fonts/fontsmanager.h

去掉热区的gsetting调用，热区功能目前暂不支持
Log: 去掉热区的gsetting调用
pms: TASK-369703

feat: 去掉热区的gsetting调用

---

src/service/impl/appearancemanager.cpp

Temporary plan, the control center will provide interfaces for dfm  to call in the future
pms: BUG-294645

feat: Adapt wallpaper settings for treeland environment

---

debian/changelog

as title
Log: bump version to 1.1.47

chore: bump version to 1.1.47

---

src/service/impl/appearancemanager.cpp
src/service/modules/subthemes/customtheme.cpp

ApplyGlobalTheme is required when switching custom themes
Bug: pms-286349

fix: invalid custom theme setting

---

misc/translations/translations/dde-appearance_zh_CN.ts
src/service/impl/appearancemanager.cpp
src/service/impl/appearancemanager.h

feat: adapt wallpaper lock

---

debian/changelog

as title
Log: bump version to 1.1.48

chore: bump version to 1.1.48

---

misc/dconfig/org.deepin.dde.appearance.json
src/service/modules/fonts/fontsmanager.cpp
src/service/modules/fonts/fontsmanager.h

Add config to override languages supported by fonts
pms: BUG-292479

feat: Add override font to support language functionality
